"""
Django settings for API_django_tp project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import environ
from pathlib import Path


# 初始化环境变量
venv = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))  # 读取.env文件

AUTH_USER_MODEL = 'accounts.User'  # 指定自定义用户模型
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-wsnwd*_t_txna^%^g+j78e4%3d2+u4pm2)@wsg$^rr_h97u158"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt",
    "django_filters",
    "machines",
    "monitor",
    #"tasks",
    "apis",
    "mocks",
    "performance",
    "drf_yasg",
    "executors",
    "projects",
    "reports",
    "testcases",
    "logs",
    "templates",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",#跨域中间件
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'common.middleware.RequestLogMiddleware',  # 自定义请求日志中间件
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, '../frontend/templates')], #vue输出目录
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0", 
        ## 以下为可选配置
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,   
            "SOCKET_TIMEOUT": 10,           
            "IGNORE_EXCEPTIONS": True,     
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",  
        },
        "KEY_PREFIX": "myapp_prod"  
    }
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "zh-Hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR.parent, 'fronted/static')] #vue输出目录
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# 允许访问的前端域名（解决跨域）
ALLOWED_HOSTS = venv.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '192.168.1.100'])
CORS_ALLOWED_ORIGINS = venv.list('CORS_ORIGINS', default=['http://localhost:8080', 'http://127.0.0.1:8080'])

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# REST Framework配置
REST_FRAMEWORK = {
    # 认证方式（JWT令牌认证）
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # 权限控制（默认登录后可访问）
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 分页配置
    'DEFAULT_PAGINATION_CLASS': 'common.pagination.StandardResultsSetPagination',
    # 过滤配置
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # 异常处理
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
}

# JWT配置
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # 访问令牌有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # 刷新令牌有效期
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Celery配置（异步任务）
CELERY_BROKER_URL = venv('CELERY_BROKER', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = venv('CELERY_BACKEND', default='redis://localhost:6379/0')
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# 告警通知配置
NOTIFY_CONFIG = {
    # 邮件配置（SendGrid）
    'email': {
        'SENDGRID_API_KEY': venv('SENDGRID_API_KEY', default=''),
        'FROM_EMAIL': venv('FROM_EMAIL', default='alarm@api-test.com'),
    },
    # 短信配置（可选）
    'sms': {
        'TWILIO_ACCOUNT_SID': venv('TWILIO_ACCOUNT_SID', default=''),
        'TWILIO_AUTH_TOKEN': venv('TWILIO_AUTH_TOKEN', default=''),
        'TWILIO_PHONE_NUMBER': venv('TWILIO_PHONE_NUMBER', default=''),
    },
    # 告警规则：连续失败3次触发告警
    'alarm_rule': {
        'CONTINUOUS_FAILURE_THRESHOLD': 3,
    }
}

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/api_monitor.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'monitor': {  # 监控模块日志
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'executors': {  # 执行引擎日志
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
# 邮件配置
EMAIL_HOST = venv('EMAIL_HOST')
EMAIL_PORT = venv.int('EMAIL_PORT')
EMAIL_HOST_USER = venv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = venv('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL=True
# 测试请求超时时间配置,执行引擎配置
TEST_REQUEST_TIMEOUT = venv.int('TEST_REQUEST_TIMEOUT', default=30)  # 测试请求超时时间，默认30秒